version: '2'
services:
  kittenserver:
    build: .
    image: kittenserver:bench
    entrypoint: '/kittenserver -cpuprofile /profile/cpu.prof -memprofile /profile/heap.prof'
    ports:
      - 8323:8323
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    links:
      - mongodb:mongodb
    volumes:
      - ./:/profile
  mongodb:
    image: mongo
    ports:
      - 27017:27017
